# Generated by Django 5.0.6 on 2025-05-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(verbose_name=255),
        ),
    ]
